In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-prediction/Heart_Disease_Prediction.csv

In [2]:
# Importing Libraries 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
# Loading Dataset
ht = pd.read_csv('/kaggle/input/heart-disease-prediction/Heart_Disease_Prediction.csv')

In [4]:
# Viewing Dataset
ht

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [5]:
# Dropping Nan Values
ht = ht.dropna()

In [6]:
# Defining features(X) and target variable (y)
X = ht.drop('Heart Disease', axis=1)
y = ht['Heart Disease']

In [7]:
# Splitting the data into test and train models
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# Perform one-hot encoding for the different columns
htencode = pd.get_dummies(ht, columns=['Sex', 'Chest pain type', 'BP', 'Cholesterol', 'Slope of ST', 'Thallium'], drop_first=True)

In [9]:
htencode

,Age,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Number of vessels fluro,Heart Disease,Sex_1,Chest pain type_2,...,Cholesterol_360,Cholesterol_394,Cholesterol_407,Cholesterol_409,Cholesterol_417,Cholesterol_564,Slope of ST_2,Slope of ST_3,Thallium_6,Thallium_7
0,70,0,2,109,0,2.4,3,Presence,True,False,...,False,False,False,False,False,False,True,False,False,False
1,67,0,2,160,0,1.6,0,Absence,False,False,...,False,False,False,False,False,True,True,False,False,True
2,57,0,0,141,0,0.3,0,Presence,True,True,...,False,False,False,False,False,False,False,False,False,True
3,64,0,0,105,1,0.2,1,Absence,True,False,...,False,False,False,False,False,False,True,False,False,True
4,74,0,2,121,1,0.2,1,Absence,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,0,162,0,0.5,0,Absence,True,False,...,False,False,False,False,False,False,False,False,False,True
266,44,0,0,173,0,0.0,0,Absence,True,True,...,False,False,False,False,False,False,False,False,False,True
267,56,0,2,153,0,1.3,0,Absence,False,True,...,False,False,False,False,False,False,True,False,False,False
268,57,0,0,148,0,0.4,0,Absence,True,False,...,False,False,False,False,False,False,True,False,True,False
269,67,0,2,108,1,1.5,3,Presence,True,False,...,False,False,False,False,False,False,True,False,False,False

In [10]:
# Dropping some columns
htencode2 = htencode.drop(['FBS over 120', 'EKG results', 'ST depression'], axis=1)

In [11]:
htencode2

,Age,Max HR,Exercise angina,Number of vessels fluro,Heart Disease,Sex_1,Chest pain type_2,Chest pain type_3,Chest pain type_4,BP_100,...,Cholesterol_360,Cholesterol_394,Cholesterol_407,Cholesterol_409,Cholesterol_417,Cholesterol_564,Slope of ST_2,Slope of ST_3,Thallium_6,Thallium_7
0,70,109,0,3,Presence,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,67,160,0,0,Absence,False,False,True,False,False,...,False,False,False,False,False,True,True,False,False,True
2,57,141,0,0,Presence,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,64,105,1,1,Absence,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,74,121,1,1,Absence,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,162,0,0,Absence,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
266,44,173,0,0,Absence,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
267,56,153,0,0,Absence,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
268,57,148,0,0,Absence,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
269,67,108,1,3,Presence,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

In [12]:
# Define a list of column names to convert to integers
convert_columns = ['Sex_1', 'Chest pain type_2', 'Chest pain type_3', 'Chest pain type_4', 'BP_100', 'Cholesterol_360', 'Cholesterol_394', 'Cholesterol_407', 'Cholesterol_409', 'Cholesterol_417', 'Cholesterol_564', 'Slope of ST_2', 'Slope of ST_3', 'Thallium_6', 'Thallium_7']

In [13]:
# Convert the specified columns to integers (0 or 1)
htencode2[convert_columns] = htencode2[convert_columns].astype(int)

In [14]:
htencode2[convert_columns]

,Sex_1,Chest pain type_2,Chest pain type_3,Chest pain type_4,BP_100,Cholesterol_360,Cholesterol_394,Cholesterol_407,Cholesterol_409,Cholesterol_417,Cholesterol_564,Slope of ST_2,Slope of ST_3,Thallium_6,Thallium_7
0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0
1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,1
2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1
3,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1
4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1
266,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1
267,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
268,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0
269,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0

In [15]:
# USING RANDOM FOREST CLASSIFIER

# Split the data (after encoding categorical variables)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
# Training a Random Forest Classifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Now, make predictions using the encoded testing data
y_pred = model.predict(X_test)